set-option -g default-terminal "xterm-256color"
setw -g mode-keys vi

bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'V' send-keys -X select-line
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection
bind-key -T copy-mode-vi 'Escape' send-keys -X cancel

bind-key -T copy-mode-vi '/' send-keys -X search-forward
bind-key -T copy-mode-vi '?' send-keys -X search-backward

bind-key -T copy-mode-vi 'h' send-keys -X cursor-left
bind-key -T copy-mode-vi 'j' send-keys -X cursor-down
bind-key -T copy-mode-vi 'k' send-keys -X cursor-up
bind-key -T copy-mode-vi 'l' send-keys -X cursor-right

bind-key -T copy-mode-vi 'H' send-keys -X start-of-line
bind-key -T copy-mode-vi 'L' send-keys -X end-of-line
bind-key -T copy-mode-vi '^' send-keys -X start-of-line
bind-key -T copy-mode-vi '$' send-keys -X end-of-line

bind-key -T copy-mode-vi 'C-b' send-keys -X page-up
bind-key -T copy-mode-vi 'C-f' send-keys -X page-down

bind-key -T copy-mode-vi 'q' send-keys -X cancel