[user]
    name = {{ user.name }}
    email = {{ secrets.git_email }}

[core]
    editor = vim
    autocrlf = input

[alias]
    st = status
    ci = commit
    co = checkout
    br = branch
    lg = log --oneline --graph --decorate

[push]
    default = simple

[pull]
    rebase = false